### ISSUE TITLE
Use `Button` from `@equinor/mad-components`

### ISSUE THREAD

**Issue by ofredstie** [equinor/hearing-test#199]
[Mad Components](https://github.com/equinor/mad/tree/main/packages/components) have button component which supports the outline variant. 

Replace local color definitions, local theme and buttons with shared components from this mono repo.

**Comment by ofredstie** [comment]
Currently blocked by changes currently in progress in #151

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.4.3      |
| Build number | 20231117.7 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Most of buttons working good, but I'm not able to start a new test.  @dansvend 

https://github.com/equinor/hearing-test/assets/128059194/8dbb6dfd-5a11-4438-8ccf-97871cbefa62

**Comment by dansvend** [comment]
There's currently something wrong with the API in the test environment 😭

**Comment by dansvend** [comment]
@SayyareHamit The API is now working in the test environment so testing continue 💪

**Comment by dansvend** [comment]
> Works as expected on V0.4.3 build 20231117.7 @dansvend

Nice 🧘 Thanks for testing 🙌
