### ISSUE TITLE
Transition to TypeScript

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#201]
Transition to TypeScript incrementally, one component at the time:

https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

## Files

- [x] #203 
- [x] #204
- [x] #205
- [x] #207
- [x] #229

**Comment by KaterynaBasik** [comment]
Can we close this issue?

**Comment by dansvend** [comment]
> Can we close this issue?

Yes👌
