### ISSUE TITLE
Tone of voice

### ISSUE THREAD

**Issue by ofredstie** [equinor/hearing-test#208]
Review the tone of voice of how the sentences in the app

**Comment by ofredstie** [comment]
"Din oversikt" vs "Mine resultater"

<img width="411" alt="Skjermbilde 2023-05-24 kl  12 01 29" src="https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/003a7932-b15c-40d6-ad86-08b161ca6312">

**Comment by ofredstie** [comment]
Mismatch between menu item text and heading text in related screen:

<img width="400" alt="image" src="https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/43999256-aa0a-4091-be92-4e5f3c9bc9fd">

<img width="430" alt="image" src="https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/cc9a02fd-c726-4ff4-9653-3fef1743ad79">

**Comment by ofredstie** [comment]
Settings page is in English:
<img width="430" alt="image" src="https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/c70390fe-75a7-402e-8047-b8de43a9e98d">

**Comment by ofredstie** [comment]
"Scanne" and "Scan":
<img width="415" alt="image" src="https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/8923c5b0-53a8-4b34-945e-224f35afc64f">

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.4.3      |
| Build number | 20231114.3 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works as expected as required. @dansvend  🐱‍🏍
