### ISSUE TITLE
Update pause menu icons

### ISSUE THREAD

**Issue by VetleW** [equinor/hearing-test#211]
Test icons for "avslutt testen", "Start hørselstesten på ny" & "ta ny lydsjekk".

[Here](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?type=design&node-id=4157-86408&t=tolwRRCLuwJ302pz-4) is the link to the proposed design change

**Comment by ofredstie** [comment]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-24 at 14 14 30](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/c8e4d953-44c3-401a-a627-d079ee37f288)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-24 at 14 17 36](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/3599cec0-ec36-43a4-bc59-1507463bbb51)

**Comment by dansvend** [comment]
@VetleW is there a better icon for "Ta ny lydsjekk" than the double checkmark?

**Comment by VetleW** [comment]
> @VetleW Could [this](https://icons.expo.fyi/MaterialIcons/headset) be used?

Ja, absolutt

**Comment by dansvend** [comment]
@VetleW Can you update the issue description with a link to Figma showing how it should look like with the new icons? After that is done this can be moved to `Ready for development` 👌

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231218.5 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works as expected. @dansvend ✨
![file_720](https://github.com/equinor/hearing-test/assets/128059194/0eb340b7-63a0-48d9-91a4-eeab4d58be57)

**Comment by dansvend** [comment]
> Works as expected. @dansvend ✨ ![file_720](https://private-user-images.githubusercontent.com/128059194/291878906-0eb340b7-63a0-48d9-91a4-eeab4d58be57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzI4ODQsIm5iZiI6MTcwMzA3MjU4NCwicGF0aCI6Ii8xMjgwNTkxOTQvMjkxODc4OTA2LTBlYjM0MGI3LTYzYTAtNDhkOS05MWE0LWVlYWI0ZDU4YmU1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMTQzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2EyNjI1MzM3Y2IzZTNmMTdhYjUyYTY4NjBhYzFkNjFhNTk1MTE0YjBiMzdlMTQyMWI2MTBjMDRkNzg5NWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._bPTGv2CqEPTLjo3p6Iwg2gBmIz-GiOB_G0DRsYif2g)

Good to hear 🙌 Thanks for testing 🙏

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
Icons for Pause menu options are updated.
