### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#216]
Add issue templates for bug reports and feature requests. Both should include a developer checklist.

**Comment by KaterynaBasik** [comment]
We already have common issue templates for new feature, bug report, or chore. 
You can start by creating a new issue from the template here https://github.com/equinor/mad-team/issues   and then move it to the right repo.

To make it easy Josh came up with the idea to [Create a scheduled github action to clone templates from a source to a target repo#279](https://github.com/equinor/mad-team/issues/279)
