### ISSUE TITLE
Sounds not being played after restarting hearing test

### ISSUE THREAD

**Issue by ofredstie** [equinor/hearing-test#218]
How to reproduce: 
1. Start a new hearing test
2. Verify that you hear the sound samples
3. Pause the test
4. Click on "Start på ny"
5. The test will now restart, but the sounds will not be played

![Skjermbilde 2023-06-05 kl  08 58 18](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/b722960f-ecdb-419a-a641-bab9cc6f0840)

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬


```
-----------------------------
| Platform     | iOS        |
| Version      | 0.4.1      |
| Build number | 20230821.4 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
The sounds played after restarting hearing test. @dansvend 🐱‍🏍

**Comment by dansvend** [comment]
> The sounds played after restarting hearing test. @dansvend 🐱‍🏍

Awesome! Thanks for testing @SayyareHamit 🚀
