### ISSUE TITLE
Remove name from login screen

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#230]
Remove Hørselsmonitorering from app logo on login screen

**Comment by dansvend** [comment]
@VetleW can you remove `Hørselsmonitorering` from the Figma file with the app logo?

**Comment by VetleW** [comment]
I've done it for these two places: [1.](https://www.figma.com/file/0Y6LDJW2LWLdHlVOF2Lg1DR2/Splash-Screens?type=design&node-id=2074-10656&t=ogCF5ReE8o31Qq40-4) [2.](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?type=design&node-id=3496-72080&t=IkJsXqcZ5pIJbbld-4)

**Comment by VetleW** [comment]
Here is the logo without text:
![Hørselstest logo](https://github.com/equinor/mad-project-hearing-test-client/assets/130735266/7e91f0cc-4f27-4e5c-b8a4-370cc809530d)

**Comment by ofredstie** [comment]
@VetleW I'm moving this issue to "Blocked" for now, until we have found out if the app name should be visible in the login screen  or not 😊

**Comment by dansvend** [comment]
Resolved by #248
