### ISSUE TITLE
Sound Check redesign

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#235]
The Sound Check on the `SoundCheckScreen` needs to ensure the patient have their headset on the correct way. During the sound check the patient should pick from which ear they hear the sound. I think we already have a design in Figma for this, but please ask the designer if the design is sufficient or should be improved upon.

**Comment by VetleW** [comment]
Her er [designet](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?type=design&node-id=4185-86158&mode=design&t=DfMONL7bsUs1CtSl-4) om jeg ikke tar feil. Ser ikke noe grunn til å endre designet foreløpig.

**Comment by dansvend** [comment]
That's correct. Sounds good 👌 I'll move this issue to `📜 Ready for development`.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.5.0      |
| Build number | 20231221.7 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works as expected, the user is able to click the button when they hear the sound.  @dansvend 🐱‍💻
![img_1578_720](https://github.com/equinor/hearing-test/assets/128059194/67c1175a-1231-4c80-a7c7-8a5b71062ef6)

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
Sound check shows one circle each for left ear and right ear.
