### ISSUE TITLE
Clean up color constants

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#236]
In `colors.ts` there are a lot of unused color constants. By removing these unused constants, we ensure a cleaner and more maintainable codebase. Additionally, this will help reduce the overall bundle size of the application.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 No functional changes - but you should verify that colors are the same as before.

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231212.2 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good in Test. @dansvend 😎

**Comment by dansvend** [comment]
> Works good in Test. @dansvend 😎

Cool 🥳  Thanks for testing 🙏
