### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#252]
The app icon should follow EDS styling.

- [x] Create new app icon following EDS

![icon](https://github.com/equinor/hearing-test/assets/47424077/61250f8c-7afa-4e92-a7b5-15d8ed4ca03e)

The app logo should be used the following places:

- [x] #352 
- [x] App Icon - Logo should be 1024x1024 png

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240212.1 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with the version above. Hearing test app has a green icon instead of pink.

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
Hearing Test app icon is updated
