### ISSUE TITLE
Button to display list of test results should be hidden when not viewing a result

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#266]
![image](https://github.com/equinor/hearing-test/assets/47424077/e58a06e7-71f8-4fda-9173-c50fff0a1df9)

**Comment by dansvend** [comment]
Closed by #318

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
No button on the left side of the header bar when showing the list of testing results.
