### ISSUE TITLE
Use `MaterialCommunityIcons`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#269]
Since `@equinor/mad-components` use `MaterialCommunityIcons` we should switch from using `MaterialIcons` to `MaterialCommunityIcons` to avoid having to import it in the project code.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 No functional changes. You should verify that icons look the same as before.

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231212.3 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good in Test. @dansvend 🐱‍🏍

**Comment by dansvend** [comment]
> Works good in Test. @dansvend 🐱‍🏍

Sweet 🧘 Thanks for testing 🙌
