### ISSUE TITLE
Send feedback to ServiceNow

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#289]
Send feedback to ServiceNow by migrating to the [CreateIncidentScreen](https://github.com/equinor/mad-expo-core/blob/main/src/screens/CreateIncidentScreen.tsx).

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
------------------------------
| Platform     | iOS         |
| Version      | 0.4.3       |
| Build number | 20231116.12 |
| Environment  | Test        |
------------------------------
```

**Comment by SayyareHamit** [comment]
The feedback function works as expected. @dansvend ✨

**Comment by dansvend** [comment]
> The feedback function works as expected. @dansvend ✨

Awesome 👌 Thanks for testing 💪
