### ISSUE TITLE
Migrate `PreTestScreen` to TypeScript

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#291]

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 I've refactored the screens before starting the test, so no need to take a hearing test. There should be no functional changes.

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.4.3      |
| Build number | 20231124.1 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good in Test. @dansvend ✔

**Comment by dansvend** [comment]
> Works good in Test. @dansvend ✔

Sweet 🧘 Thanks for testing 🙏
