### ISSUE TITLE
Use `Typography` from `@equinor/mad-components`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#296]
Use `Typography` from `@equinor/mad-components` by doing the following:

- [x] Replace `Text` from `react-native`
- [x] Replace `Typography` from `mad-expo-core`
- [x] Use Equinor font for navigation header title and header back title
- [x] Delete project implementation of `Typography`

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231128.1 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good in Test. @dansvend 🐱‍👤

**Comment by dansvend** [comment]
> Works good in Test. @dansvend 🐱‍👤

Awesome 🤩 Thanks for testing 🙏
