### ISSUE TITLE
Improve the experience for internal testers

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#299]
Improve the experience for internal testers so that they don't need to listen to all test sound for test the whole test flow including pages after the test. Some proposals are:

1. Click a button to complete the test.
2. Add a mute audio button in the `TestScreen`

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231128.5 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
The mute button doesn't work, I can still hear the sound while doing hearing test. @dansvend 👀

**Comment by dansvend** [comment]
> The mute button doesn't work, I can still hear the sound while doing hearing test. @dansvend 👀

Are you sure you're on the correct build? It works on my phone 🙌 When the button icon is a speaker with a cross, that's the current state so no sounds should be audible. When the button icon is a speaker sounds should be audible.

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
Mute button works fine.
