### ISSUE TITLE
Refactor `Card` component

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#300]
Refactor the `Card` component which is used as the building block for the `TestCard` and `NavigationItem` components used on the `DefaultScreen` and `TestScreen`.

![Image](https://github.com/equinor/hearing-test/assets/47424077/e274ede5-4f90-48d6-9ed0-a78d0638b5e8)

### Requirements
- Same look and feel as before

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231125.1 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works as required. @dansvend 🐱‍🏍

**Comment by dansvend** [comment]
> Works as required. @dansvend 🐱‍🏍

Good to hear 😄 Thanks for testing 💪
