### ISSUE TITLE
Use `LinearProgress` from `@equinor/mad-components`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#301]
- [x] Replace `ProgressBar` and `ProgressAnimationBar` with `LinearProgress` from `equinor/mad-components`
- [x] Delete `LinearProgress`
- [x] Delete `ProgressAnimationBar`

**Comment by dansvend** [comment]
Blocked by equinor/mad#286

**Comment by SayyareHamit** [comment]
works good. @dansvend 🐱‍👤

**Comment by dansvend** [comment]
> works good. @dansvend 🐱‍👤

Nice 👌 Thanks for testing 🥼
