### ISSUE TITLE
Use `alert` from `@equinor/mad-components`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#302]
- [x] Replace `Alert` from `react-native` with `alert` from `@equinor/mad-components`.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231127.1 |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Works good as expected. @dansvend ✨

**Comment by dansvend** [comment]
> Works good as expected. @dansvend ✨

Sweet 🧘 Thanks for testing 👌
