### ISSUE TITLE
Use `CircularProgress` from `@equinor/mad-components`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#309]
- [x] Replace `Spinner` from `mad-expo-core` with `CircularProgress` from `@equinor/mad-components`

**Comment by SayyareHamit** [comment]
Works as expected. @dansvend 🐱‍🏍

**Comment by dansvend** [comment]
> Works as expected. @dansvend 🐱‍🏍

Awesome 😍 Thanks for testing 💪
