### ISSUE TITLE
Migrate `TestScreen` to TypeScript

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#310]
- [x] Add correct types
- [x] Rewrite from Class to Functional component
- [x] Use Redux Hooks like `useDispatch` and `useSelector` instead of `connect`, `mapDispatchToProps` and `mapStateToProps`.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 All of the functionality on the screen when taking a hearing test should be tested.

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.5.0      |
| Build number | 20240126.7 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
@dansvend  Here are the errors I discovered during testing. I assume these can be fixed quickly
 - The mute button is not working anymore.
- The time displayed in the result is not accurate. I started testing around 11, but it shows differently here. 
![image](https://github.com/equinor/hearing-test/assets/128059194/1876fb2a-3000-4a6b-b64a-ef123d1dc959)

**Comment by dansvend** [comment]
> @dansvend Here are the errors I discovered during testing. I assume these can be fixed quickly
> 
> * The mute button is not working anymore.
> * The time displayed in the result is not accurate. I started testing around 11, but it shows differently here.
>   ![image](https://private-user-images.githubusercontent.com/128059194/300774932-1876fb2a-3000-4a6b-b64a-ef123d1dc959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODg0NTYsIm5iZiI6MTcwNjY4ODE1NiwicGF0aCI6Ii8xMjgwNTkxOTQvMzAwNzc0OTMyLTE4NzZmYjJhLTMwMDAtNGE2Yi1iNjRhLWVmMTIzZDFkYzk1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwODAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmZkZmMxYzU4OWRjNjM3ZGRkZDk5YTc4YzNkM2QyZmIxMDFkYzU0MTE0ZDRkYThiMjI4OTAwZjY5N2YzYmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LJd8F8d6eZP8SEkI0KMy7SXaHPDkL35hRRgxq9ktz8g)

This has now been fixed and is available for testing in the following build:

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.5.0      |
| Build number | 20240130.1 |
| Environment  | Test       |
-----------------------------
```

Regarding the timestamp, this depends on when you fetch the test which happens when you enter the test screen. Did you enter the test screen at 9:33 and then pressed the button to start the test around 11?

**Comment by SayyareHamit** [comment]
I retested this issue again, the mute button and the correct time is now displayed on the portal. The app is working as expected. 
@dansvend ✨

**Comment by dansvend** [comment]
> I retested this issue again, the mute button and the correct time is now displayed on the portal. The app is working as expected. @dansvend ✨

Awesome! Thanks for testing 💪
