### ISSUE TITLE
Update test completion feedback

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/hearing-test#317]
### Description

As a User, I want to get information about the status when the test is completed.

We've got feedback that users don't remember they have seen/read a message on a "Testen er fullført" screen that says  "You will be contacted by...". So we have agreed on new texts for screens.

There are  4 possible results when the test is completed:
- OK  (Result screen message: Testen er fullført. Dette ser fint ut! Det er ikke oppdaget en endring i hørselen siden forrige måling)
- Outlier (Result screen message: Her ble det litt krøll. Dette kan see ut som en feilmåling. Ta ny test eller kontakt sykepleier)
- Not Ok ( Result screen message: Testen er fullført. Vennligst kontakt sykepleier. Det er oppdaget en endring i hørselen din)
- Failure - in case of some technical issues the app cant't send data/get a result

### Design

Result screens  text needs to be updated in Figma

### AcceptanceCriteria

- [ ] when the test is completed, user sees the screen corresponding to one of the results

### Additionalinfo

We need to think about a way to test all possible results. 

### DefinitionofDone

- [ ] Acceptance criteria met
- [ ] Code has been reviewed
- [ ] Unit test(s) are created and passing
- [ ] Functional tests created and passing

**Comment by KaterynaBasik** [comment]
I have updated the issue description based on yesterday's meeting with the customer

**Comment by dansvend** [comment]
@anheri After taking a test i got this from the API which is not correct:

```TSX
{
...
result: null
}
```

According to the API I should get one of the following:

```CS
public enum AnalysisFlag
    {
        Undefined = 0,
        Ok = 1,
        Outlier = 2,
        NotOk = 3
    };
```

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.5.0      |
| Build number | 20240103.6 |
| Environment  | Test       |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Whenever I press the 'Jeg hører lyden' button during testing, It should display 'Dette ser fint ut' on the screen after the testing is completed, but now I'm getting 'vennligst kontakt sykepelier' every time. This might be an issue with the API. Could you please have a look for this? @anheri

**Comment by sir-larsen** [comment]
![image](https://github.com/equinor/hearing-test/assets/76153505/28cf86b9-825a-4f36-8969-a0a50843b00b)

API seems to returns Ok as result when testing manually @SayyareHamit

**Comment by QiJin-Bouvet** [comment]
Tested hearing 3 times, always get OK (Testen er fullført. Dette ser fint ut! Det er ikke oppdaget en endring i hørselen siden forrige måling).

**Comment by dansvend** [comment]
We got approval from the team to merge this.
