### ISSUE TITLE
Refactor `TestResultScreen`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#321]
Use redux hooks `useSelector` and `useDispatch` instead of `mapDispatchToProps`, `mapStateToProps` and `connect`.

**Comment by SayyareHamit** [comment]
Works good in Test. @dansvend 🐱‍👤

**Comment by dansvend** [comment]
> Works good in Test. @dansvend 🐱‍👤

Awesome 🚀 Thanks for testing 💪
