### ISSUE TITLE
The confirm box should be visible

### ISSUE THREAD

**Issue by SayyareHamit** [equinor/hearing-test#322]
### **What happened?**
When I clicked break button while hearing test is ongoing, the alert box pops up with four options. when I clicked "Avslutte testen" button, than a confirm box pops up behind the first alert box. Same happend with "Start hørselstesten på ny" and "Ta ny lydsjekk" options.
![288345788-141ac6fc-193e-4e76-b954-772ac52ad5e1](https://github.com/equinor/hearing-test/assets/128059194/b2fd9ebe-8a1b-4eea-8a0c-1d2b669ab50c)

### **Steps to reproduce**
1. Start hearing test
2. When hearing test starts, click pause button, than alert box with four options pops up.
3. Than click "Avslutte testen", a confirm box pops up behind the first alert box.

### **Expected results**
When a user clicks any options on the alert box, the confirm box belong to that option should be visible. The user shouldn't click "Fortsette hørselstesten" first, than click "Ja" or "Nei" button on a confirm box to proceed.

### **Actual results**
The confirm box is hidden following the alert box.
Have a look for the image above.

### **Environment details**
Test environment.

**Comment by dansvend** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20231207.2 |
-----------------------------
```

**Comment by dansvend** [comment]
> Works as expected on all iOS devices. @dansvend 🐱‍👤

Awesome 😍 Thanks for testing 🙏

**Comment by QiJin-Bouvet** [comment]
Tested with version 0.6.0  Build number 20240213.2
Confirm box is in front of the Pause menu.
