### ISSUE TITLE
Extract reaction time from prod data

### ISSUE THREAD

**Issue by anheri** [equinor/hearing-test#337]

**Comment by sir-larsen** [comment]
Data can be found in the export_data branch in the files HearingDataProd.json and HearingDataProdFormatted.json

**Comment by sir-larsen** [comment]
Found bug, moving back to in progress

**Comment by sir-larsen** [comment]
Fixed semantic error. Data can now be found in export_data branch in the files HearingDataProdNew.json and HearingDataProdNewFormatted.json

**Comment by dansvend** [comment]
Thanks for doing this @sir-larsen 💪 I'm closing this issue as completed.
