### ISSUE TITLE
Upgrade to Expo 50

### ISSUE THREAD

**Issue by tormodAase** [equinor/hearing-test#338]
https://expo.dev/changelog/2024/01-18-sdk-50

Upgrade should lead to minimal changes in the app from the user's perspective

**Comment by tormodAase** [comment]
Ready to test!

20240124.3
0.5.0
@SayyareHamit

**Comment by SayyareHamit** [comment]
Works good in Test. @tormodAase

**Comment by QiJin-Bouvet** [comment]
Merged and released in R 0.6.0.
