### ISSUE TITLE
Ignore `preDelayMs` if previous node was not heard

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#343]
Currently, each node in the hearing test includes a preDelayMs value that specifies the amount of time to wait before playing the node's sound after the previous node has finished. However, if the patient did not hear the previous sound, there is no need to wait the full preDelayMs before playing the next sound.

This update will improve the efficiency of the hearing test by ignoring the preDelayMs value when the previous node was not heard, resulting in a shorter overall test time.

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240202.2 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Hearing test lasted 6'26'' for no sound heard (no click), which is shorter than before.

**Comment by dansvend** [comment]
> Hearing test lasted 6'26'' for no sound heard (no click), which is shorter than before.

Nice to hear 👌 Thanks for testing 🙌
