### ISSUE TITLE
Create splash screen

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#345]
Create a new splash screen for Hørselstest which works with the new login screen in [@equinor/mad-core](https://www.npmjs.com/package/@equinor/mad-core).

**Comment by EmilieOlsen** [comment]
![image](https://github.com/equinor/hearing-test/assets/111871753/57ab5b71-75b9-4eff-a2c6-5bef044e86a6)

https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=1944%3A14260&mode=design&t=7K385bmAeGmXquU5-1

**Comment by dansvend** [comment]
> ![image](https://private-user-images.githubusercontent.com/111871753/301845922-57ab5b71-75b9-4eff-a2c6-5bef044e86a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODY2OTMsIm5iZiI6MTcwNjg4NjM5MywicGF0aCI6Ii8xMTE4NzE3NTMvMzAxODQ1OTIyLTU3YWI1YjcxLTc1YjktNGVmZi1hMmM2LTViZWYwNDRlODZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxNTA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGM4ZTg1ZjY5YzlmN2Q3ODQ3Y2QxYjg2MjM5ZmRmOGYzMDdlYzgzOGZiYjRmZjJjNThlNTM5MmFlZmI1N2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pn3FeLjNDzSDhRCeO7YNeTCE3NUHABH-B9oawjr30DI)
> 
> https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=1944%3A14260&mode=design&t=7K385bmAeGmXquU5-1

Thanks a bunch, Emilie 🙏
