### ISSUE TITLE
Migrate from `expo-barcode-scanner` to `expo-camera`

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#346]
Use [this guide](https://github.com/expo/fyi/blob/main/barcode-scanner-to-expo-camera.md) to migrate from the deprecated `expo-barcode-scanner` to `expo-camera`.

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬 You should test if it's still possible to scan the barcode to proceed to the hearing test.

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240202.3 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
Scan barcode and start hearing test works fine.

**Comment by dansvend** [comment]
> Tested with the build above. Scan barcode and start hearing test works fine.

Sweet! Thanks for testing 💪
