### ISSUE TITLE
Stuck on spinner after canceling stopping test

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#356]
How to reproduce:
1. Press the pause button during a hearing test
2. Press on "Avslutte testen" or "Start på ny"
3. Press on "Nei"

This should continue the test.

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240216.4 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with build above.
By choose 'Nei' after "Avslutte testen"/ "Start hørselstesten på ny"/ "Ta ny lydsjekk", app goes back to the Pause menu without hanging.
