### ISSUE TITLE
Unable to post test

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#361]
Tested with build 20240216.4 in TEST env.
Reproduce steps:

1. start a hearing test
2. click 'Jeg hører lyden' for some times
3. pause the test several time and continue
4. finish the hearing test

Expected: Test result is sent successfully
Actually: Failed to send test result, error 400

![image](https://github.com/equinor/hearing-test/assets/47424077/ce3d3639-31f6-4f91-b14e-02e98b04ad44)

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240229.1 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with build 20240229.1 in TEST env.
Not able to reproduce the problem anymore.

**Comment by dansvend** [comment]
> Tested with build 20240229.1 in TEST env. Not able to reproduce the problem anymore.

Awesome! Thank you so much for testing 🙏
