### ISSUE TITLE
Unable to start a second test during the same session

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#367]
A user is unable to start a second test during the same session. This is due to the test state not being cleared after finishing a test.

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240308.3 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
User is able to start a second testing.
BUT, once the user pause and choose to start a new hearing test, the new test complete in several seconds, which is wrong.

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.5.0      |
| Build number | 20240318.4 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with the build above in TEST env.
- No stuck with Pause menu
- able to start a second testing
- the new hearing testing started from pause menu works as normal

**Comment by dansvend** [comment]
> Tested with the build above in TEST env.
> 
> * No stuck with Pause menu
> * able to start a second testing
> * the new hearing testing started from pause menu works as normal

Sweet! Thanks for testing and bringing the good news 😄
