### ISSUE TITLE
Show test result screen after sending an unsent test

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#371]

**Comment by dansvend** [comment]
@QiJin-Bouvet 

This is ready for testing 👩‍🔬

**Test procedure**
1. Turn off WiFi and 5G after fetching a new test.
2. Let the test finish while muted
3. Close app completely
4. Open app
5. The default screen of the app should prevent you from starting a new test by telling you have an unsent test. Click "Send" which should give you test results of the analysis of your test.

```
-----------------------------
| Platform     | iOS        |
| Environment  | Test       |
| Version      | 0.6.0      |
| Build number | 20240321.1 |
-----------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with the build above.
Worked as expected.

**Comment by dansvend** [comment]
> Tested with the build above. Worked as expected.

Nice! Thanks for testing 🙏
