### ISSUE TITLE
Upgrade Hearing Test to Expo SDK 51

### ISSUE THREAD

**Issue by tormodAase** [equinor/hearing-test#383]

**Comment by tormodAase** [comment]
Should be ready for test in 20-40 minutes! Check the PR for build number

**Comment by tormodAase** [comment]
No changes should be expected. Pay extra attention to camera functionality in the app.

**Comment by QiJin-Bouvet** [comment]
Tested with v 0.7.1 build 20240514.1
- Camera works good
- Hearing test results looks wrong
@dansvend Can you take a look at this to see whether it relates to the Expo SDK upgrading

![Image](https://github.com/equinor/hearing-test/assets/88656616/9902ef21-2b24-4621-aabb-b796365b9f0d)

**Comment by tormodAase** [comment]
Putting this in blocked while waiting for @dansvend to get back from vacation!

**Comment by dansvend** [comment]
> Tested with v 0.7.1 build 20240514.1
> 
> * Camera works good
> * Hearing test results looks wrong
>   @dansvend Can you take a look at this to see whether it relates to the Expo SDK upgrading
> 
> ![Image](https://private-user-images.githubusercontent.com/88656616/330706384-9902ef21-2b24-4621-aabb-b796365b9f0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjE1NzIsIm5iZiI6MTcxNjQ2MTI3MiwicGF0aCI6Ii84ODY1NjYxNi8zMzA3MDYzODQtOTkwMmVmMjEtMmIyNC00NjIxLWFhYmItYjc5NjM2NWI5ZjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwNDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYTk1MmZiNDBiMGJkYjc5MTMwMmI5NDkxZmJhM2YxNDc1NzJkYTFjN2ZkZTZhMThlNjFmNjUyZmU0NWU4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S5zyxcDfiGWbP_Ls-yo_HGi6diE7A78kUHhAc6chw2w)

This result graph seems fine when looking at you previous test results in the hearing portal 🙌

**Comment by dansvend** [comment]
> Putting this in blocked while waiting for @dansvend to get back from vacation!

This seems fine. You may resume this task 💪

**Comment by QiJin-Bouvet** [comment]
New hearing api only play tests on frequency 3k, 4k, 6k for both ears. So the test results are correctly.
Therefore, no function broken. Move card to in QA lane.
