### ISSUE TITLE
Add audio files to app bundle

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#424]
Instead of downloading audio files used during the hearing test from the API we reduce the number of potential errors. This also makes it possible to remove the storage account where the audio files are hosted.

**Comment by dansvend** [comment]
@QiJin-Bouvet This is ready for testing 🧪 

```
-------------------------------
| Platform     | iOS          |
| Environment  | Test         |
| Version      | 0.7.7        | 
| Build number | 2024.1004.47 |
-------------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with build 2024.1004.47 in TEST env
No function broken.

**Comment by dansvend** [comment]
@QiJin-Bouvet The code for the API has been updated and is running in test environment, which means the app code needed some adjustments. So this needs a new round of testing in the following build:

```
-------------------------------
| Platform     | iOS          |
| Environment  | Test         |
| Version      | 0.7.7        | 
| Build number | 2024.1009.48 |
-------------------------------
```

**Comment by QiJin-Bouvet** [comment]
Tested with build 2024.1009.48 in TEST.
No function broken.

**Comment by dansvend** [comment]
Thanks for testing 🙌
