### ISSUE TITLE
Add app version to telemetry

### ISSUE THREAD

**Issue by dansvend** [equinor/hearing-test#426]
Add `app-version` as a custom property to all events logged to Application Insights.

**Comment by dansvend** [comment]
@QiJin-Bouvet This is ready for testing in `2024.1003.45`

**Comment by QiJin-Bouvet** [comment]
app version is shown in the CustomEvents in AppInsight/hearing-client-test/Logs

![image](https://github.com/user-attachments/assets/31e46365-3ba6-41dc-8b42-54a2b165616f)

**Comment by dansvend** [comment]
> app version is shown in the CustomEvents in AppInsight/hearing-client-test/Logs
> 
> ![image](https://private-user-images.githubusercontent.com/88656616/373204569-31e46365-3ba6-41dc-8b42-54a2b165616f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTc5MDksIm5iZiI6MTcyNzk1NzYwOSwicGF0aCI6Ii84ODY1NjYxNi8zNzMyMDQ1NjktMzFlNDYzNjUtM2JhNi00MWRjLThiNDItNTRhMmIxNjU2MTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDEyMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YzQ1MmI5NTFjZGRlNWExMmYzYWY2NzM1MWIwMGE3YjMwYTNhNWY2NDMzZTZkNzNkYjQ5MzY2NjFhOWQ3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CgZ5JLcAAckNDYYZd1aAn42b2drSc21jnccX6DKVTlM)

Thank you so much for testing, @QiJin-Bouvet 🙏
